# Generated by Django 5.0.4 on 2025-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcase',
            name='last_seen_time',
            field=models.TimeField(null=True),
        ),
    ]
