# Generated by Django 5.0.4 on 2025-08-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='family',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('family', 'Family'), ('volunteer', 'Volunteer')], default='user', max_length=20),
        ),
    ]
