# Generated by Django 5.0.4 on 2025-08-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_account_family_alter_account_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='name',
        ),
    ]
