# Generated by Django 5.0.4 on 2025-10-13 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reportcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcase',
            name='assisted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportcase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Closed - Safe', 'Closed - Safe'), ('Closed - Deceased', 'Closed - Deceased'), ('Closed - Unresolved', 'Closed - Unresolved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
