# Generated by Django 5.0.4 on 2025-09-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_account_family_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('family', 'Family'), ('volunteer', 'Volunteer'), ('police', 'Police')], default='user', max_length=20),
        ),
    ]
