# Generated by Django 5.0.4 on 2025-10-14 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reportcase_assisted_by_alter_reportcase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAssistance',
            fields=[
                ('assistance_id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='core.reportcase')),
                ('volunteer', models.ForeignKey(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assistances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'volunteer')},
            },
        ),
    ]
