# Generated by Django 5.0.4 on 2025-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reportcase_status_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
