# Generated by Django 5.0.4 on 2025-08-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_username_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='username',
        ),
    ]
