# Generated by Django 5.0.4 on 2025-10-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reportassistance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcase',
            name='assisted_by',
        ),
    ]
