# Generated by Django 5.0.4 on 2025-09-03 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCase',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('last_seen_date', models.DateField()),
                ('last_seen_location', models.CharField(max_length=255)),
                ('clothing', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Missing', 'Missing'), ('Ongoing', 'Ongoing'), ('Resolved', 'Resolved')], default='Missing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
