# Generated by Django 5.0.4 on 2025-09-12 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reportcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='report_media/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.reportcase')),
            ],
        ),
    ]
