# Generated by Django 5.0.4 on 2025-10-16 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSighting',
            fields=[
                ('sighting_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date_seen', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='core.reportcase')),
                ('volunteer', models.ForeignKey(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_sightings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
