# Generated by Django 5.0.4 on 2025-09-14 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reportmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='contactNo',
            new_name='contact_num',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='family',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
