# Generated by Django 5.0.4 on 2025-10-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reportsighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='sighting_media/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.reportsighting')),
            ],
        ),
    ]
