# Generated by Django 5.0.4 on 2025-10-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usernotification_is_deleted'),
        ('core', '0008_sightingmedia'),
    ]

    operations = [
    ]
