# Generated by Django 5.0.4 on 2025-09-18 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_contactno_family_contact_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='full_name',
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteer_id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=255)),
                ('location_area', models.CharField(max_length=255)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
