# Generated by Django 5.0.4 on 2025-10-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251017_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('family', 'Family'), ('volunteer', 'Volunteer'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('new_message', 'New Message'), ('report_updated', 'Report Updated'), ('assistance_started', 'Assistance Started')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
