# Generated by Django 5.0.4 on 2025-10-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251017_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsighting',
            name='time_seen',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('report_created', 'Report Created'), ('report_info_updated', 'Report Information Updated'), ('report_updated', 'Report Updated (Sightings)'), ('status_changed', 'Status Changed'), ('new_message', 'New Message')], max_length=50),
        ),
    ]
