# Generated by Django 5.0.4 on 2025-10-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_target_role_alter_notification_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='target_role',
            field=models.CharField(default='both', max_length=20),
        ),
    ]
