# Generated by Django 5.0.4 on 2025-10-20 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target_role',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='target_role',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('status_changed', 'Status Changed'), ('new_message', 'New Message')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reportsighting',
            name='volunteer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_sightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
