# Generated by Django 5.0.4 on 2025-10-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reportsighting_time_seen_alter_notification_action'),
        ('core', '0013_remove_notification_target_role_and_more'),
    ]

    operations = [
    ]
