# Generated by Django 5.0.4 on 2026-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20251021_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Closed - Safe', 'Closed - Safe'), ('Closed - Deceased', 'Closed - Deceased'), ('Closed - Unresolved', 'Closed - Unresolved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
