# Generated by Django 5.0.4 on 2026-02-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_reportcase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcase',
            name='status',
            field=models.CharField(choices=[('PendingOTP', 'Pending OTP'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Closed - Safe', 'Closed - Safe'), ('Closed - Deceased', 'Closed - Deceased'), ('Closed - Unresolved', 'Closed - Unresolved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ReportVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='core.reportcase')),
            ],
        ),
    ]
